#!/usr/bin/env python3
"""PreToolUse: block hand-edits to frontend/api/generated/.

That directory is regenerated by `pnpm -C frontend generate-client`; manual
edits get clobbered. Enforces the AGENTS.md rule for Claude Code. Exit 2
blocks the tool call and feeds stderr back to the agent.
"""

import json
import os
import sys

GUARDED = "/frontend/api/generated/"


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0  # unparseable input -> never block

    file_path = (data.get("tool_input") or {}).get("file_path")
    if not file_path:
        return 0

    project_dir = data.get("cwd") or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    norm = os.path.abspath(os.path.join(project_dir, file_path)).replace(os.sep, "/")

    if GUARDED in norm:
        print(
            f"Blocked: {file_path} is under frontend/api/generated/, which is "
            "generated from the backend OpenAPI schema. Change the backend "
            "endpoint instead, then run `pnpm -C frontend generate-client`. "
            "(See AGENTS.md.)",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
