"""add spotify_tokens table

Revision ID: 36df67a68339
Revises: b37bb7cb8d13
Create Date: 2026-03-30 18:11:17.165304

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36df67a68339"
down_revision = "b37bb7cb8d13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spotify_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("refresh_token", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spotify_tokens")
    # ### end Alembic commands ###
